project:
  name: churn-e2e
  random_seed: 42

data:
  raw_csv_path: data/raw/telco_churn.csv
  target_col: Churn Value
  id_cols: ["CustomerID"]
  test_size: 0.2

model:
  type: xgboost   # options: logistic_regression, random_forest, gradient_boosting

  params:
    logistic_regression:
      max_iter: 300
      class_weight: balanced

    random_forest:
      n_estimators: 400
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1
      class_weight: balanced
      random_state: 42
      n_jobs: -1

    gradient_boosting:
      max_iter: 300
      learning_rate: 0.05
      max_depth: 6
      min_samples_leaf: 20
      l2_regularization: 0.0
      random_state: 42

    xgboost:
      n_estimators: 600
      learning_rate: 0.05
      max_depth: 4
      subsample: 0.9
      colsample_bytree: 0.9
      reg_lambda: 1.0
      random_state: 42
    

train:
  threshold: 0.5              # decision threshold for churn label

artifacts:
  model_dir: models
  reports_dir: reports
  model_filename: model.joblib
  metrics_filename: metrics.json

mlflow:
  enabled: false
  experiment_name: churn-e2e

